### ISSUE TITLE
yarn test failing due to superstruct dependency

### ISSUE THREAD

**Issue by ebramanti** [solana-labs/dapp-scaffold#10]
When I pull a fresh copy of this repo, I get the following error from Jest:
```
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    TypeError: superstruct.instance is not a function

      1 | import type { PublicKey } from "@solana/web3.js";
      2 | 
    > 3 | import Wallet from "@project-serum/sol-wallet-adapter";
        | ^
      4 | import { Transaction } from "@solana/web3.js";
      5 | import { Button, Modal } from "antd";
      6 | import EventEmitter from "eventemitter3";

      at Object.<anonymous> (node_modules/@solana/web3.js/src/connection.ts:45:3)
      at Object.<anonymous> (node_modules/@project-serum/sol-wallet-adapter/dist/index.js:4:15)
      at Object.<anonymous> (src/contexts/wallet.tsx:3:1)
      at Object.<anonymous> (src/routes.tsx:3:1)
      at Object.<anonymous> (src/App.tsx:3:1)
      at Object.<anonymous> (src/App.test.tsx:3:1)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

I think it has something to do with the `@solana/web3.js` dependency being different in the `@project-serum` sub-dependencies, but not quite sure.

**Comment by ebramanti** [comment]
> Bump!

Just opened a PR for this, sorry for the delay I just got around to it 😬
